### ISSUE TITLE
Extension menu is blank after fresh chrome store install

### ISSUE THREAD

**Issue by dpedu** [ollien/Spectabular#24]
Possibly related:

`Error in response to storage.get: TypeError: Cannot read property 'darkMode' of undefined
at Object.callback (chrome-extension://dfbebiockmbbeaookjfmdafnjdbimcnm/popup.js:533:26)
at Object.callback (chrome-extension://dfbebiockmbbeaookjfmdafnjdbimcnm/popup.js:13:24)`

**Comment by ollien** [comment]
Should be fixed with 0.530.1. Let me know if it fixes it.

**Comment by dpedu** [comment]
Looks fixed!

**Comment by ollien** [comment]
Perfect! Thansk @dpedu!
